In [1]:
import pandas as pd

In [2]:
INPUT_FILE = r"../data/drug_consumption_transformed.csv"
OUTPUT_FILE = r"../data/drug_consumption_numeric.csv"

In [3]:
df = pd.read_csv(INPUT_FILE)
df

,age,gender,education,country,ethnicity,nscore,escore,oscore,ascore,cscore,choc
0,35-44,Female,Professional certificate/diploma,UK,Mixed-White/Asian,39,36,42,37,42,CL5
1,25-34,Male,Doctorate degree,UK,White,29,52,55,48,41,CL6
2,35-44,Male,Professional certificate/diploma,UK,White,31,45,40,32,34,CL4
3,18-24,Female,Masters degree,UK,White,34,34,46,47,46,CL4
4,35-44,Female,Doctorate degree,UK,White,43,28,43,41,50,CL6
...,...,...,...,...,...,...,...,...,...,...,...
1880,18-24,Female,"Some college or university, no certificate or ...",USA,White,25,51,57,48,33,CL4
1881,18-24,Male,"Some college or university, no certificate or ...",USA,White,33,51,50,48,30,CL4
1882,25-34,Female,University degree,USA,White,47,30,37,31,31,CL6
1883,18-24,Female,"Some college or university, no certificate or ...",USA,White,45,26,48,32,22,CL5
1884,18-24,Male,"Some college or university, no certificate or ...",Republic of Ireland,White,31,53,56,50,45,CL6

In [ ]:
COLUMN_ORDERS = {
    "age": ["18-24", "25-34", "35-44", "45-54", "55-64", "65+"],
    "education":  ["Left school", "Some college or university, no certificate or degree", "Professional certificate/diploma",
                    "University degree", "Masters degree", "Doctorate degree"],
}

In [5]:
for col, orders in COLUMN_ORDERS.items():
    n_levels = len(orders)
    mapping = dict(zip(orders, range(n_levels)))
    df[col] = df[col].map(mapping)
df

,age,gender,education,country,ethnicity,nscore,escore,oscore,ascore,cscore,choc
0,2,Female,2,UK,Mixed-White/Asian,39,36,42,37,42,CL5
1,1,Male,5,UK,White,29,52,55,48,41,CL6
2,2,Male,2,UK,White,31,45,40,32,34,CL4
3,0,Female,4,UK,White,34,34,46,47,46,CL4
4,2,Female,5,UK,White,43,28,43,41,50,CL6
...,...,...,...,...,...,...,...,...,...,...,...
1880,0,Female,1,USA,White,25,51,57,48,33,CL4
1881,0,Male,1,USA,White,33,51,50,48,30,CL4
1882,1,Female,3,USA,White,47,30,37,31,31,CL6
1883,0,Female,1,USA,White,45,26,48,32,22,CL5
1884,0,Male,1,Republic of Ireland,White,31,53,56,50,45,CL6

In [6]:
df.to_csv(OUTPUT_FILE, index = False)